// <auto-generated />
using System;
using CMEManagementService.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMEManagementService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251017153712_coursecontroller")]
    partial class coursecontroller
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("CMEManagementService.Models.Entites.EducationCourse", b =>
                {
                    b.Property<Guid>("EducationCourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CreditHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EducationCourseId");

                    b.ToTable("EducationCourses");
                });

            modelBuilder.Entity("CMEManagementService.Models.Entites.Personnel", b =>
                {
                    b.Property<Guid>("PersonnelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PersonnelId");

                    b.ToTable("Personnel");

                    b.HasDiscriminator().HasValue("Personnel");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CMEManagementService.Models.Entites.PersonnelParticipation", b =>
                {
                    b.Property<Guid>("PersonnelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EducationCourseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfParticipations")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonnelId", "EducationCourseId");

                    b.HasIndex("EducationCourseId");

                    b.ToTable("PersonnelParticipations");
                });

            modelBuilder.Entity("CMEManagementService.Models.Entites.Doctor", b =>
                {
                    b.HasBaseType("CMEManagementService.Models.Entites.Personnel");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Doctor");
                });

            modelBuilder.Entity("CMEManagementService.Models.Entites.Nurse", b =>
                {
                    b.HasBaseType("CMEManagementService.Models.Entites.Personnel");

                    b.Property<string>("Certification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Nurse");
                });

            modelBuilder.Entity("CMEManagementService.Models.Entites.PersonnelParticipation", b =>
                {
                    b.HasOne("CMEManagementService.Models.Entites.EducationCourse", "EducationCourse")
                        .WithMany("Participations")
                        .HasForeignKey("EducationCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMEManagementService.Models.Entites.Personnel", "Personnel")
                        .WithMany("Participations")
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationCourse");

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("CMEManagementService.Models.Entites.EducationCourse", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("CMEManagementService.Models.Entites.Personnel", b =>
                {
                    b.Navigation("Participations");
                });
#pragma warning restore 612, 618
        }
    }
}
