// <auto-generated />
using System;
using CMEManagementService.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMEManagementService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("CMEManagementService.Models.Entites.EducationCourse", b =>
                {
                    b.Property<Guid>("EducationCourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("EducationCourseId");

                    b.ToTable("EducationCourses");
                });

            modelBuilder.Entity("CMEManagementService.Models.Entites.Personnel", b =>
                {
                    b.Property<Guid>("PersonnelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PersonnelId");

                    b.ToTable("Personnel");

                    b.HasDiscriminator().HasValue("Personnel");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CMEManagementService.Models.Entites.Doctor", b =>
                {
                    b.HasBaseType("CMEManagementService.Models.Entites.Personnel");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Doctor");
                });

            modelBuilder.Entity("CMEManagementService.Models.Entites.Nurse", b =>
                {
                    b.HasBaseType("CMEManagementService.Models.Entites.Personnel");

                    b.Property<string>("Certification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Nurse");
                });
#pragma warning restore 612, 618
        }
    }
}
